### ISSUE TITLE
Action 10 (HISCOM): Continue testing duplicate detection and investigate other options for being able to detect 'the majority' (Ryonen Butcher, ALA)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#10]

**Comment by AaronWilton** [comment]
Is this our definition of duplicate or the more "record/?modelling" perspective?

I still think the oneous lies with us to record the accession number when we receive specimens from another collection via exchange/gift. 

However, can perhaps see utility in attempting a back filling of that data.
