### ISSUE TITLE
Action 13 (HISCOM): Follow-up issue with displaying Conservation Status in the AVH (ALA, Michael Hope)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#13]
Currently there is only 1 field 'Country Conservation' in AVH - it should ideally be renamed 'Conservation Status' and have the status for the jurisdiction the specimen was collected in. There should be pre-existing ALA/AVH GitHub issue/s on this one.

**Comment by nielsklazenga** [comment]
Already done: https://github.com/AtlasOfLivingAustralia/avh-hub/issues/57. Just needs to be actioned.

**Comment by DNAdl8** [comment]
It appears Nick has actioned AtlasOfLivingAustralia/avh-hub#57. I guess it just needs to be tested. Just state conservation is being made available, NOT EPBC
