### ISSUE TITLE
Action 14 (HISCOM): Update logos and Dept. links on the 'About AVH' page under 'Participating herbaria' (ALL)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#14]

**Comment by DNAdl8** [comment]
There are two pages where logos, Dept names etc need reviewing by all participating herbaria. These include (test site) - under 'Participating herbaria:
http://data.rbg.vic.gov.au/avh/ and http://data.rbg.vic.gov.au/avh/index.php/about/

**Comment by ainsleyongit** [comment]
Most organisations have guidelines about how their logos need to be represented—I would guess that most of those displayed on the AVH are undersized according organisational style guides.

**Comment by DNAdl8** [comment]
Alison indicated in the June 2017 Teleconference that she has updated DNA, BRI and HO logos and Dept. links.

**Comment by nielsklazenga** [comment]
I think this had to do with the launch of the Australasian Virtual Herbarium, so we can just close this issue at the meeting.
