### ISSUE TITLE
Action 15 (HISCOM): Investigate if downloads can be reordered to a default based on HISPID 6.0 classes (Michael Hope)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#15]

**Comment by nielsklazenga** [comment]
Most of the HISPID classes are Darwin Core classes, which makes sense following for all of ALA, so I would focus on that, rather than HISPID classes. There is only one HISPID class, **Transaction**, that is currently  used in AVH. I expect this will remain so.

**Comment by m-hope** [comment]
A general github issue to reorder the fields in the download file into a more sensible order: https://github.com/AtlasOfLivingAustralia/downloads-plugin/issues/10

**Comment by m-hope** [comment]
Note: HISPID 6.0 is identical to DwC...

**Comment by nielsklazenga** [comment]
Merging with issue #40.
