### ISSUE TITLE
Action 17 (HISCOM): Check ALA collectory pages are up-to-date (ALL)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#17]

**Comment by DNAdl8** [comment]
Attached are instructions on editing collection or institution pages on the
[Uploading UpdatingCollectionsInformation_final.pdf…]()
 ALA (Feb 2016).

**Comment by DNAdl8** [comment]
see https://github.com/hiscom/business/issues/39

**Comment by ben3000** [comment]
As of 1 July, our department will be changing its name to Biodiversity, Conservation and Attractions. This will likely cause our domain name to change from dpaw.wa.gov.au to bca.wa.gov.au. On or after 1 July, we'll need to update the ALA collectory to reflect the change, which is currently still in discussion.

**Comment by nielsklazenga** [comment]
Linking to issue #39 and closing.
