### ISSUE TITLE
Action 20 (HISCOM): Make minor amendments to AVH static pages (Niels Klazenga)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#20]
Minor amendments include removing map, update logo/dept. links, minor edits to Help Pages (Donna to provide)

**Comment by DNAdl8** [comment]
Email to Alison dated 20/01/17. Recognising changes can't be made until Australasian VH is about to go live.
On each page, the ‘Contact us’ link is not working.

AVH Help / Data page http://data.rbg.vic.gov.au/avh/index.php/help/data/
•	Phenology – DNA is providing Phenology through our BioCAse Provider, appears as ‘reproductive condition’ in the AVH. At present the website indicates that only MEL and NSW deliver this info.
•	Conservation status – I think more info is required here. AVH displays both Commonwealth (EPBC) and State/Territory legislation. It needs to be clear what classification systems are being used i.e. EPBC uses IUCN, NT uses IUCN, WA use something else etc…. This info is important. Also, it doesn’t appear the info is up-to-date on the ALA pages for the State/Territory links? i.e. http://collections.ala.org.au/public/show/dr655. BUT this is an ALA issue..
•	Taxonomy/Taxon names in AVH – ‘Australian Plant Census’ link needs updating.
•	Ecoregion – Interim Register of Marine and Nonmarine Genera (IRMNG) link is broken.
•	Vegetation type -  National Vegetation Information System link is broken.
•	Overall, some links from this page are not linking to the intended heading on the Using AVH page, instead they are linking to the top of the page, so some inconsistencies there.

AVH Help / Using AVH page http://data.rbg.vic.gov.au/avh/index.php/help/using-avh/
•	Results / Refine results – the customize filters dialog has changed and possibly should replace the old version.
•	Records tab / Downloads – the downloads interface has changed and needs to be reflected on this page. See http://avh-test.ala.org.au/download?searchParams=%3Fq%3Dlsid%253Ahttp%253A%252F%252Fid.biodiversity.org.au%252Fnode%252Fapni%252F2915822%26qc%3Ddata_hub_uid%3Adh9&targetUri=/occurrences/search ......and http://avh-test.ala.org.au/download/confirm?searchParams=%3Fq%3Dlsid%253Ahttp%253A%252F%252Fid.biodiversity.org.au%252Fnode%252Fapni%252F2915822%26qc%3Ddata_hub_uid%3Adh9&targetUri=%2Foccurrences%2Fsearch&downloadType=records. The download format possibly needs further explanation i.e. Full Darwin Core, ALA Legacy Format, customised download. Ben also suggested having a HISPID 6.0 format.
•	Map tab / Download map – this dialog box has slightly changed so I’m unsure whether it’s worth updating – see what you think. 
•	Record detail – there is a ‘Contact curator’ button on this page next to the ‘Flag an issue’ button, so this should be mentioned.

**Comment by acvaughan** [comment]
All these changes were made some time back, with the exception of the conservation status stuff, because I couldn't get my head around what was going on there (I'm still not sure).
