### ISSUE TITLE
Action 23 (HISCOM): Contact Peter Wilson regarding vocabularies in the Yellow Book for substrate, soil and topography (Donna)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#23]

**Comment by ben3000** [comment]
@DNAdl8 has there been any progress on this?

**Comment by ben3000** [comment]
This was about vocabularies for substrate, soil and topography.

**Comment by ben3000** [comment]
Donna to contact the Yellow Book authors and note that the best way they could contribute is to publish the vocabulary for their substrate, soil and topography terms online, we can commence using it in CHAH member specimen databases.

**Comment by nielsklazenga** [comment]
I believe Donna has asked, but it is not available yet. Closing this for now.
