### ISSUE TITLE
Action 28 (HISCOM): Clarify / bring to CHAHs attention, who is the custodian of the datasets in NSL? (Donna, Anne)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#28]
HISCOM were of the understanding that this requires ratification from CHAH. 
Donna raised this with CHAH at the AGM in Auckland.

**Comment by afuchs1** [comment]
A paper was prepared for CHAH by Michelle and Anne covering the issues around data governance for all Flora datasets in the NSL. I understand CHAH have requested that ABRS (Anthony Whalen) in conjunction with NSL prepare a paper building on this. We have had an initial meeting.
