### ISSUE TITLE
Action 30 (HISCOM): Summarise requirements for providing images to the ALA/AVH (Gillian, Ryonen)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#30]

**Comment by GillBrown** [comment]
Requirements emailed to Ryonen and Donna 8/9/2017. 
Metadata requirements still needed to be added.

**Comment by DNAdl8** [comment]
Requirements for adding images to AVH_ALA sent by Gill 8/9/2017
[Requirements for adding images to AVH_ALA.DOCX](https://github.com/hiscom/business/files/1373777/Requirements.for.adding.images.to.AVH_ALA.DOCX)

**Comment by DNAdl8** [comment]
Email from Michael regarding the metadata requirements:
'In answer to the question of what metadata is required for images, the ALA system doesn’t enforce a minimum (ie: you can still add an image without metadata, however we do strongly recommend that you at least include: license or rights information, photographer, and rights holder (if different to photographer)'.
