### ISSUE TITLE
Action 31 (HISCOM): Provide example on GitHub to prepare and deliver images to ALA/AVH i.e. URL, min metadata required (Niels)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#31]

**Comment by nielsklazenga** [comment]
I sent a long email to HISCOM and MAHC long before the HISCOM meeting.

**Comment by DNAdl8** [comment]
Thanks Niels. Can you find that email and post the content here please? Emails tend to get lost - ta

**Comment by nielsklazenga** [comment]
I just forwarded it to Ryonen this morning. She is working on it. This was a duplicate of #29.

**Comment by DNAdl8** [comment]
Thanks
