### ISSUE TITLE
Action 32 (HISCOM): ALA to provide list of images for us to provide

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#32]

**Comment by DNAdl8** [comment]
Michael has offered to distribute a list to HISCOM of images to provide to the ALA/AVH. ACTION from June Teleconference

**Comment by ben3000** [comment]
Not a priority of HISCOM or MAHC. We're tired of waiting.

**Comment by ben3000** [comment]
(Just kidding.)
