### ISSUE TITLE
Action 34 (HISCOM): Recommendation to CHAH that MAHC and HISCOM meet at CHR in 2018 to coordinate with the SPNCH and TDWG in Dunedin from 25th August to 2nd September 2018 (Donna, Frank)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#34]
Donna and Frank raised this with CHAH at their meeting in Auckland. Waiting on formal approval..

**Comment by AaronWilton** [comment]
this was approved by CHAH - with not on timing and time that staff will be away from office  (but should wait for official reply)

**Comment by DNAdl8** [comment]
CHAH minutes
-	Recommendation to CHAH that MAHC, and HISCOM meet at CHR 2018 to co ordinate with SPNHC. CHAH endorses this.

**Comment by bone89** [comment]
How do I open this another way the open link provided does not work
