### ISSUE TITLE
Action 2 (MAHC/HISCOM): In AVH test Advanced Search the look up table for 'Botanical Group' includes animals and this needs to be fixed before it goes to production (Michael/Aaron)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#36]
Michael emailed Aaron in regards to this 11/11/2016...
HI Aaron,

Was just going through the HISCOM action items and realised that Action 2 (issue regarding the inclusion of animal categories in the Botanical Groups) is because the NZVH data includes animals and as all the data from NZVH is pulled into AVH it includes these animals... (you can list them here: http://avh-test.ala.org.au/occurrences/search?q=kingdom:Animalia, and if you scroll to the Attribution facet, you can see they're all from NZ institutions)... Any idea how we deal with these?  Should they be provided in a different dataset?

**Comment by AaronWilton** [comment]
hmm - the test site is not working properly for me to drill into the records.

However, the records i did see are plants and have been incorrect classified by the name matching process (e.g., Haastia)

**Comment by DNAdl8** [comment]
Michael is going to follow this up with Aaron offline Re: 98 Animal names from NZ in AVH. ACTION from June Teleconference

**Comment by nielsklazenga** [comment]
Launch has happened, so closing.

**Comment by DNAdl8** [comment]
2017 AGM comment - needs Artificial Intelligence to recognise taxonomy so this is not going to be resolved to perfection. A lot of the problems coming from addition of New Zealand institutions because Australian taxonomy is set to override New Zealand taxonomy. Problems als around fungi names. ALA are aware they cannot get it 100% right but the current resolution is that you cannot search for animals in advanced search but names will still exist in the facets.
