### ISSUE TITLE
Action 3 (MAHC/HISCOM): Add functionality to the AVH to be able to zoom to the extent of records after searching on a taxon or multiple taxa (Michael)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#37]

**Comment by DNAdl8** [comment]
Confirmed at 2017 AGM in Melbourne that this issue was not entirely completed. Michael is following up.

**Comment by DNAdl8** [comment]
[https://github.com/hiscom/business/issues/59](url)

**Comment by nickdos** [comment]
Suggestion to have a user preference to allow user to see either:
- view extent of all records all the time
- view extent of records when records are inside AUS & NZ, otherwise zoom out to AUS & NZ (current functionality)

**Comment by ben3000** [comment]
TODO Link ALA spatial-hub or avh-hub issue here.

**Comment by ben3000** [comment]
This looks like it has been fixed.
