### ISSUE TITLE
Action 4 (MAHC/HISCOM): Collections Managers to check they are registered with ALA and are receiving alerts (MAHC Collection Managers)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#38]

**Comment by AaronWilton** [comment]
This was raised with the NZ herbaria at the AGM last week and some have actioned already.

**Comment by nielsklazenga** [comment]
Merging with issue #39.

**Comment by DNAdl8** [comment]
2017 AGM comment - Alerts and annotation technical issues are technically resolved now. Should be getting alerts now and Michael to run through it later. RECOMMEND set alerts to get all annotations to check that you are getting alerts and then change it back to your institution.
