### ISSUE TITLE
Action 5 (MAHC/HISCOM): Annotations - check Collectory Institutions contacts plus Collection Managers are signed up for and are receiving alerts (Michael)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#39]
Ryonen circulated an email with regards to 'updating ALA collectory page information 07/11/2016..

During the past year ALA made changes to the annotation alerts system so that collections staff could mark a record as being correct (verified) if the query brought against it was found to be in error (i.e. it is a true outlier not a coordinate error etc.). It has become evident recently that the alerts for record annotations weren’t triggering anymore and I raised this with ALA last week. It appears that they added new statuses to the annotations to support the verification workflow and the status that used to trigger the alerts (user_assertions: “true”) isn’t used any more. It’s been registered as a bug and will be fixed ASAP; I’ll let you know when it’s resolved. 

In the meantime, if you could check the records at your institution in the following way, you can see whether there are any annotations outstanding:

1. On the ALA homepage (http://www.ala.org.au/), click ‘Browse data sets’ in the ‘Data sets’ box.
2. From there (http://www.ala.org.au/data-sets/) click ‘Advanced Search’.
3. In the Advanced search tab (http://biocache.ala.org.au/search#tab_advanceSearch), select your institution or collection in ‘Find records from the following institution or collection’ and click ‘Search’.
4. On the retrieved Occurrence Records page, scroll down through the facets on the left hand side until you get to ‘Assertions’.
5. Under ‘Has user assertions’ there will be two boxes:
- No assertions
- Unconfirmed
6. The ‘Unconfirmed’ assertions are the new ones you probably haven’t received.

Looking at PERTH and NSW as examples there aren’t many there (5 and 8, respectively), which is good, but please use this manual check for user assertions until the automatic notification system is up and running again. This is probably a good time also to make sure that your institution has their Alerts notification system properly set up in ALA (i.e. that the appropriate people are receiving the alerts you want at intervals that ensure rapid response and data correction/verification).

**Comment by DNAdl8** [comment]
Email from Michael Hope 11/11/2016.....
Following on from Ryonen’s email regarding ALA alerts, a number of people at HISCOM reported that while they are listed in their respective collections as a contact and editor, they don’t have the ability to edit their collectory information.  After a bit of investigation, it turns out that as an editor, your ALA account which (for historical reasons) is separate to the contacts list, must have the same email address and be assigned the EDITOR role.  

If any of you do not appear to be able to update your collectory information even though you are listed as a contact/editor (or even if you aren’t), please let me know and I can update your ALA account with the correct permissions.  

For reference, I have also included a guide developed by Alexis Tindall on how to edit your collectory pages.
[UpdatingCollectionsInformation_final.pdf](https://github.com/hiscom/business/files/608116/UpdatingCollectionsInformation_final.pdf)

**Comment by nielsklazenga** [comment]
Just reporting that the alerts on annotations are working again (have been for a couple of months).

**Comment by GillBrown** [comment]
Are they? I haven't been getting any and I checked my subscriptions this week and they are all ok.

**Comment by nielsklazenga** [comment]
Yes, they are definitely coming in. There probably haven't been any for the records you subscribe to (I assume that is BRI records). I am subscribing to annotations on all AVH records. The last alert I got was last night:

![image](https://user-images.githubusercontent.com/4694550/31483715-3bc93914-af79-11e7-86e1-4a39069e6223.png)

**Comment by GillBrown** [comment]
Yes, I am only subscribing to BRI records. Ok, great thanks Niels.

**Comment by DNAdl8** [comment]
2017 AGM comment - Alerts and annotation technical issues are technically resolved now. Should be getting alerts now and Michael to run through it later. RECOMMEND set alerts to get all annotations to check that you are getting alerts and then change it back to your institution.
