### ISSUE TITLE
Action 6 (MAHC/HISCOM): From Ben Richardson's suggestion, add HISPID 6.0 as a download option from the Downloads page (Michael)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#40]

**Comment by DNAdl8** [comment]
See #15

**Comment by nielsklazenga** [comment]
That doesn't make sense. Terms that are not in Darwin Core are not delivered to AVH, so "HISPID 6.0" downloads are exactly the same as Darwin Core downloads. The ABCD loan and exchange terms we have been using are now in the [GGBN Loan extension](http://rs.gbif.org/extension/ggbn/loan.xml), so they can just be added to the extended/customisable download.
