### ISSUE TITLE
Action 7 (MAHC/HISCOM): Weed alerts - Use QLD weeds lists as a test case for weed alerts (Gill, Ryonen, Michael)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#41]
This involves adding a weeds list to http://lists.ala.org.au/public/speciesLists and setting up the alerts.

**Comment by GillBrown** [comment]
Melinda Laidlaw (BRI's weedspotter co-ordinator) tried several times to set this up unsuccessfully. She contacted them about a glitch, which wasn’t able to be solved at that time. She will have another go before our meeting in Melbourne.

**Comment by DNAdl8** [comment]
Gill to follow up

**Comment by GillBrownBRI** [comment]
'Weeds listing Queensland Government' species list was updated by Miles on 21/10/2016. Cannot see how to subscribe to alerts for this list (https://lists.ala.org.au/speciesListItem/list/dr927).

**Comment by ben3000** [comment]
Michael is Michael Hope.

**Comment by ben3000** [comment]
This has been replaced with an ALA project.

**Comment by GillBrownBRI** [comment]
Background - trying to get alerts of observations of species of weeds from a species list to support QLD Weed Spotter project. Wasn't possible in 2016 so raised issue then.

**Comment by nickdos** [comment]
Just on https://lists.ala.org.au/speciesListItem/list/dr927 - to create an email alert for that list, click the button on that page labelled "View Occurrence records" and on the "Records" tab, click the button "Alerts", then on the popup click the option "Get email alerts for new". Note, this requires being logged in to the ALA.
