### ISSUE TITLE
Action 8 (MAHC/HISCOM): Work up some examples on host/parasite interactions and how HISPID 6.0 handles it (Niels?)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#42]
I can't recall who put their hand up for this?

**Comment by nielsklazenga** [comment]
https://github.com/hiscom/hispid/issues/125

**Comment by DNAdl8** [comment]
2017 AGM comment - Covered by DarwinCore not HISPID. Keith has been working on it and it is easily send able in DarwinCore.
