### ISSUE TITLE
Action 10 (MAHC/HISCOM): Explore how genbank data can be linked to specimens in the AVH, and what field it should be linked on (Ben, Jo Birch)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#44]
i.e. catalogue number, or a suite of fields....

**Comment by ben3000** [comment]
No progress on this so far.

**Comment by nielsklazenga** [comment]
I think the brief was to explore how to find sequences in GenBank that are made from specimens that have records in AVH. Linking to GenBank from AVH is trivial, as we've got the `associatedSequences` field for that. MEL has been delivering links to GenBank for the last three years.

**Comment by DNAdl8** [comment]
Genbank data can't be queried, how to pull into records - Ben reported hasn't progressed much further. Jo B report current status GenBank accession numbers can be made available for these that are provided in the associatedSequences field. iDigBio have been having a discussion with GenBank about this exact issue. Talking about ways to link.
2017 AGM Action 2 Shelly research what has been happening with iDigBio and report to Jo/Ben and the group and link to 2016 Action 10

**Comment by DNAdl8** [comment]
[https://github.com/hiscom/business/issues/53](url)

**Comment by ben3000** [comment]
Replaced by #84.
