### ISSUE TITLE
Action 14 (MAHC/HISCOM): Formulate a way to supply vouchered [hero] images against taxa (MAHC and HISCOM)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#48]

**Comment by DNAdl8** [comment]
See #32

**Comment by nielsklazenga** [comment]
Why on earth would we want to do that?

**Comment by DNAdl8** [comment]
To try and find an image for all taxa and also find good images for the most iconic taxa. Three methods to set an image - by default, voting system to upgrade image,..  This is ready to go but just needs to be released. It will still be a manual process the images. If you see an image that is not correct you can flag an issue and indicate the species identification wrong. This will then remove it from that species page and put it in limbo until data provider verifies or refutes issue flag. To add a flag, click on the thumbnail of images that are incorrect and go to record page. 
2017 AGM Action 7 - Michael to circulate lists of all taxa that don't have an image and top 200 species pages.

**Comment by DNAdl8** [comment]
[https://github.com/hiscom/business/issues/58](url)

**Comment by ben3000** [comment]
See #82.
