### ISSUE TITLE
Action 16 (MAHC/HISCOM): Provide a list of the minimum metadata data required to provide images to the ALA/AVH (Michael)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#50]

**Comment by m-hope** [comment]
Currently there is no system enforced minimum requirements for image metadata (ie: you can still add an image with no metadata), however it is recommended that you at least include: license or rights information, photographer and rights holder (if different to photographer).

**Comment by nielsklazenga** [comment]
Thanks Michael, 
We can have our own metadata guidelines, just like for AVH. Creator and copyright are Australian government requirements for web pages, so we should make that required too. For other terms it is going to depend on the type of image. For the GPI images, for example, all relevant metadata is already either in the AVH record or embedded in the image (although a lot of the latter might disappear when you alter the image). But we can have different sets of fields for different types of images.
