### ISSUE TITLE
Action 17 (MAHC/HISCOM): Recommendation to CHAH that MAHC and HISCOM meet at CHR in 2018 to coordinate with the SPNCH and TDWG conference in Dunedin from 25th August to 2nd September 2018 (Donna, Frank)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#51]
#34

**Comment by DNAdl8** [comment]
CHAH minutes
-	Recommendation to CHAH that MAHC, and HISCOM meet at CHR 2018 to co ordinate with SPNHC. CHAH endorses this.

**Comment by nielsklazenga** [comment]
I suggest we skip the HISCOM meeting next year. If something important comes up, we can always have a side meeting during the SPNHC–TDWG conference.
