### ISSUE TITLE
Action 2: Research what has been happening with iDigBio and report to the group (Shelley) 

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#53]

**Comment by DNAdl8** [comment]
Email from Shelley 25th Oct 2017:
There has been a little bit of progress, mostly due to the ingestion team brining in the Guelph BIOUG datasets. I've activated the Sequences search option in production, so its now easier to find these:
https://www.idigbio.org/portal/search?rq={"associatedsequences":{"type":"exists"}}
Mike Trizna also recently gave a talk at TDWG about this:
https://doi.org/10.3897/tdwgproceedings.1.20320

The broad summary is that its still really hard and we're not quite sure what do with this information, but we might be slowly getting to the point of doing something like this:

https://github.com/iDigBio/research-project-ideas/issues/12

using specimen based data.

**Comment by DNAdl8** [comment]
Hi everyone –
Information from iDigBio about the progress being made in the US – see this webinar and the email below:

Linking Genetic Data to and from Symbiota portals – Andrew Miller (MiCC) December 16, 2016[edit]
Webinar Recording 
An overview of how to add genetic data to records in Symbiota portals and how to use the LinkOut feature in GenBank to link back to these records
http://idigbio.adobeconnect.com/p2z3zl4uf8d/


Cheers-
Shelley

**Comment by DNAdl8** [comment]
[https://github.com/hiscom/business/issues/44](url)

**Comment by ben3000** [comment]
Completed.
