### ISSUE TITLE
Action 11: go through document that CCC wrote about the delivery of images to the ALA and edit, then circulate to all groups. Niels to include template for the data (Nicole, Michael, Niels)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#62]

**Comment by nielsklazenga** [comment]
Audubon Core required terms:
* https://tdwg.github.io/ac/termlist/#ac_metadataLanguage
* https://tdwg.github.io/ac/termlist/#ac_metadataLanguageLiteral
* https://tdwg.github.io/ac/termlist/#dc_type
* https://tdwg.github.io/ac/termlist/#dcterms_type
* https://tdwg.github.io/ac/termlist/#dc_rights
* https://tdwg.github.io/ac/termlist/#dcterms_rights

ALA also requires:
* http://purl.org/dc/terms/creator
* http://purl.org/dc/terms/license

See http://rs.gbif.org/extension/ac/audubon.xml or https://tdwg.github.io/ac/termlist/ for other terms that can be used.

**Comment by elywallis** [comment]
Discussion paper from 2016 produced after Biological Collections Workshop (HISCOM and FCIG combined)
[HISCOMFCIG_DiscussionPaper_ImageDelivery_11032016(2).docx](https://github.com/hiscom/business/files/2537333/HISCOMFCIG_DiscussionPaper_ImageDelivery_11032016.2.docx)

**Comment by ben3000** [comment]
See #82.

**Comment by nielsklazenga** [comment]
Thanks Ely, hadn’t seen this before.

Ben, what do you reckon? Could we use this is the basis for discussion? It looks pretty good to me and would save a lot of time. We can always add stuff to it.

Niels

**Comment by ben3000** [comment]
Yep that makes a lot of sense.

**Comment by nielsklazenga** [comment]
I realise just now that this might be the document the CCC wrote.

**Comment by ben3000** [comment]
See #87.
