### ISSUE TITLE
Action 14: Shared Collaborative Environment for MAHC, HISCOM and CHAH

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#65]

**Comment by nielsklazenga** [comment]
What does this mean?

**Comment by afuchs1** [comment]
My memory is this was about collaborative editing, repositories for procedures, how to docs etc. The main issue was that Departments block such things as Google docs so not everyone can participate in cloud based stuff.

**Comment by DNAdl8** [comment]
Anne is correct - a central repository for MAHC, FCIG, HISCOM.. We acknowledged that HISCOM was happy with the HISCOM wiki for minutes etc and GitHub for our Actions... Its more for the other groups to access documents etc... An example of this was an image document that Alexis had compiled and other things the CCC's put together..
See the minutes... I need to chase up Nicole and Frank to coordinate this... OR BEN?
http://hiscom.rbg.vic.gov.au/wiki/Joint_HISCOM/MAHC/FCIG_2017_Melbourne#Document_storage_and_data_sharing_between_groups

**Comment by ben3000** [comment]
Which institutions are blocking what software? We need basic data to make any kind of decision.

**Comment by ben3000** [comment]
Discussed at CHAH and HISCOM in Perth in 2019. More to come.

**Comment by ben3000** [comment]
I'm closing this as a result of CHAH's acceptance of the Microsoft Teams environment hosted and supported by Blair, Pina and Niels at RBG Victoria. Thanks everyone, this is a great outcome.
