### ISSUE TITLE
Action 7 (HISCOM): Check with Nicole Fisher (FCIG Chair) and Gen Walker-Smith (Faunal CCC) if they would like to be added to the HISCOM list or be emailed in when appropriate (Ryonen Butcher)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#7]

**Comment by bone89** [comment]
Action,7(HISCOM):CHECK with Nicole Fisher(FCIG Chair) and Gen Walker-Smith(Faunal CCC) if they would like to be added to HISCOM LISTor be emailed in when appropriate (Ryonen Butcher)#7

**Comment by ryonen** [comment]
I emailed both Gen and Nicole and both would like to be included on the HISCOM list please. Ryonen.

**Comment by bone89** [comment]
Yes I would love too be added
