### ISSUE TITLE
Action 5: Investigate handling of Typified Names in DwC and searching of them in the AVH (Michael)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#70]
Michael emailed 24/10/2017
Hi guys,

I’m going through my actions from last week and one of the discussions centred around Typified Names… I’d like to see if I understand the concept before I start the ball rolling on getting something implemented.

My understanding is that for type specimens (I am assuming any specimen labelled as any of the types) an additional field provides a “typified name” which, I think, is the taxonomic name given to the specimen when it became the type??? This name could be different to the Supplied Name (which is the current taxonomic name of the specimen when it was last curated) and the Matched Name (which is the current taxonomic name of the specimen according to the ALA name index).

The request from HISCOM is that the ALA indexes and allows searching on the typified name in the AVH… if we implemented the name toggle switch in the name section of the Advanced Search page, perhaps we could have 3 options: (Matched, Supplied, Typified)?
Or have I got this completely wrong?

Cheers,

Michael.

**Comment by DNAdl8** [comment]
Niels response 24/10/2017
Hi Michael,
You got it essentially right.
In the back end provided name, matched name and typified name are just three different terms, but in the advanced query form I would put provided and matched name in a toggle together and use a separate field, as it is an entirely different concept.
So we could have a ‘Type’  heading with two fields under it, ‘Type status’ (which is the current processed type_status field) and ‘Typified name’.

Michael: Just to clarify, the Typified Name should not be matched to a current name… ie: we want to search on the raw name.

Niels: Yes, you don’t have to do any name resolution. Maybe allow a terminal wildcard.

**Comment by nickdos** [comment]
Issue in avh-hub, currently fixed but not deployed: https://github.com/AtlasOfLivingAustralia/avh-hub/issues/72

**Comment by ben3000** [comment]
This was fixed in the AVH hub.
