### ISSUE TITLE
Action 7: Email providers to start delivering Bush Blitz name to AVH. (Niels). Reinstate wildcard to search Bush Blitz names in AVH (Michael)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#72]
The list is still loaded on the Bushblitz website: http://bushblitz.org.au/resources/. Under the resources heading, bottom of the list is “Bush Blitz Point data name formats”

**Comment by ben3000** [comment]
What field are we to deliver data using?

**Comment by ben3000** [comment]
This has been dealt with in the technical addendum update.
