### ISSUE TITLE
Document what the community would like from ALA for delivery and linking of specimen images

### ISSUE THREAD

**Issue by ben3000** [hiscom/business#82]
HISCOM to document what the community's preferred technical specification is for the provision and linking of specimen images into occurrence records held in ALA. The resulting document should be in HISCOM's Business wiki, and contain some or all of the following.

* Types of images for the ALA to handle (specimen, field, taxon etc)
* Linking of images to other ALA resources (AVH, Floras, BIE etc)
* What is displayed with images (image metadata) etc
* Understanding of the ALA technical considerations (size, format, import/export)
* For the community, what are the priorities for delivery (hero images, gaps, etc)

**Comment by elywallis** [comment]
I have suggested the following changes to the description of this issue to make it clearer what you're asking ALA for:

- ALA to provide clear recipes/methods/pipelines for upload of images.
- ALA to provide advice on whether the image upload pipeline is different (and how) for upload of images to be visible on: occurrence records (in Biocache, AVH), species profile pages  (in BIE), profiles platform/eFlora (in Profiles). Images for field sites, habitat etc yet to be decided. 
- ALA to work with community to determine what data is displayed with images (image metadata) etc
- ALA to provide advice about technical considerations for image files (size in pixel dimensions, filesize, format such as tiff, jpg or png)
- For the community to decide: what are the priorities for delivery (hero images, gaps, etc)

**Comment by ben3000** [comment]
Gill is going to trial both CloudStor and Amazon S3 and report back to HISCOM as part of HISCOM 2019 AGM.
