### ISSUE TITLE
Action 5 (2019): Develop a revised Herbarium Exchange data protocol based on Darwin Core Text Archives

### ISSUE THREAD

**Issue by ben3000** [hiscom/business#89]
The revised data exchange protocol would be Darwin Core Text Archives and contain permit data, when possible. This would replace earlier approaches such as HISPID 3 data files because that data standard has been superseded, and downloads from BioCASE as it is intended that all BioCASE providers should eventually be decommissioned.

**Comment by ben3000** [comment]
Relies on the outcome of #88.

**Comment by nielsklazenga** [comment]
This is just a comment to see if the Teams integration works. I will remove it later.

**Comment by ben3000** [comment]
This was delivered at the 2020 CHAH AGM, see https://hiscom.github.io/exchange-guide/.
