### ISSUE TITLE
Action 9 (HISCOM): Investigate options for deleting records (Michael Hope)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#9]

**Comment by DNAdl8** [comment]
Currently don't auto delete. If a record is deleted an image is deleted with it and other information ahnging off a record. Soft delete - not an option..

**Comment by DNAdl8** [comment]
To permanently delete a record/s in the AVH contact data_management@ala.org.au from the data custodian

**Comment by AaronWilton** [comment]
Is this expected to change?  We do not track records that have had changes in security level or are removed for other reasons to a level where we can contact the ALA every time this happens, plus it opens the chance of missing/forgetting, nor is that a good use of time...  hoping this is a short term solution?

**Comment by nielsklazenga** [comment]
This is the solution. Deletion of records should never become routine.

**Comment by AaronWilton** [comment]
well i don't think it is a good long term solution...

**Comment by nielsklazenga** [comment]
This is just for the data that is delivered via me. I want to keep deletions separate from the aggregation (as does ALA). ALA has a few different ways that records can be deleted, so just talk with Miles about the NZ data that is delivered via you.

**Comment by nielsklazenga** [comment]
This has been discussed to death – since the Canberra meeting in 2012 – and is getting very repetitive, so let's just close the issue.
